export default {
    accountVerification: "Xác minh tài khoản",
    enterAuthentication: "Nhập mã xác thực đã gửi đến số điện thoại của bạn", 
    resend: "Gửi lại",
    confirm: "Xác thực",
    productionPlan: "Kế hoạch sản xuất",
    notification: "Thông báo",
    remindWork: "Nhắc việc",
    profile: "Thông tin người sử dụng",
    logOut: "Đăng xuất",
    executionTime: "Thời gian thực hiện",
    codePlan: "Mã kế hoạch",
    placeOfImplementation: "Địa điểm thực hiện",
    workContent: "Nội dung công việc",
    seeDetails: "Xem chi tiết",
    performTheWork: "Thực hiện công việc",
    timeStartTimeEnd: "Thời gian bắt đầu - Thời gian kết thúc",
    tomorrow: "Ngày mai", 
    level: "Mức độ",
    noraml: "Bình thường",
    important: "Quan trọng",    
    doItNow: "Thực hiện ngay", 
    content: "Nội dung",
    perform: "Thực hiện",
    video: "Video",
    takePhoto: "Chụp ảnh",
    image: "Hình ảnh",
    finish: "Hoàn thành",
    profile: "Profile",
    phoneNumber: "Số điện thoại",
    fullName: "Họ tên",
    address: "Địa chỉ",
    evaluate: "Đánh giá",
    position: "Chức vụ",
    changePassword: "Đổi mật khẩu",
    doneAt: "Thực  hiện lúc:",
    doneOnDay: "Thực hiện vào các ngày",
    welcomeBack: "Chào mừng trở lại",
    signIn: "Đăng nhập hệ thống",
    passWord: "Mật khẩu",
    forgotPassWord: "Quên mật khẩu?",
    newUser: "Người dùng mới?",
    logIn: "Đăng nhập",
    registration: "Đăng kí",
    changePassword: "Thay đổi mật khẩu",
    confirm: "Xác nhận",
    oldPassword: "Mật khẩu cũ",
    newPassword: "Mật khẩu mới",
    confirmNewPassword: "Xác nhận mật khẩu mới",
    wrongUsernameOrPassword: "Tên đăng nhập hoặc mật khẩu sai!",
    youHaveNotEnteredTheOldPassword: "Bạn chưa nhập mật khẩu cũ!",
    youHaveNotEnteredThNewPassword: "Bạn chưa nhập mật khẩu mới!",
    youHaveNotConfirmedNewPassword: "Bạn chưa xác nhận mật khẩu mới!",
    theOldPasswordIsNotCorrect: "Mật khẩu cũ chưa đúng!",
    newPasswordAndConfirmationDoNotMatch: "Mật khẩu mới và xác nhận không trùng khớp!",
    passwordChangeHasNotBeenSuccessful: "Thay đổi mật khẩu không thành công!",
    newPasswordMustHaveAtLeast4Characters: "Mật khẩu mới phải có ít nhất 4 kí tự!",
    changePasswordSuccessfully: "Thay đổi mật khẩu thành công!",
    seeMore: "Xem tiếp"
}
