export default {
    accountVerification: "Xác minh tài khoản",
    enterAuthentication: "Nhập mã xác thực đã gửi đến số điện thoại của bạn", 
    resend: "Gửi lại",
    confirm: "Xác thực",
    productionPlan: "Kế hoạch sản xuất",
    notification: "Thông báo",
    remindWork: "Nhắc việc",
    profile: "Profile",
    logOut: "Đăng xuất",
    executionTime: "Thời gian thực hiện",
    codePlan: "Mã kế hoạch",
    placeOfImplementation: "Địa điểm thực hiện",
    workContent: "Nội dung công việc",
    seeDetails: "Xem chi tiết",
    performTheWork: "Thực hiện công việc",
    timeStartTimeEnd: "Thời gian bắt đầu - Thời gian kết thúc",
    tomorrow: "Ngày mai", 
    level: "Mức độ",
    noraml: "Bình thường",
    important: "Quan trọng",    
    doItNow: "Thực hiện ngay", 
    content: "Nội dung",
    perform: "Thực hiện",
    video: "Video",
    takePhoto: "Chụp ảnh",
    image: "Hình ảnh",
    finish: "Hoàn thành",
    profile: "Profile",
    phoneNumber: "Số điện thoại",
    fullName: "Họ tên",
    address: "Địa chỉ",
    evaluate: "Đánh giá",
    position: "Chức vụ",
}
